import { Inter } from 'next/font/google';
import './globals.css';

/* const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
}); */

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${inter.variable} antialiased`}>{children}</body>
        </html>
    );
}
